version: "3.5"

services:
  postgre:
    container_name: postgre
    image: postgres:13.1
    ports:
      - 5432:5432
    environment:    
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
   postgres_data: